apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert --provider=openshift -o openshift.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: server
    name: server
  spec:
    ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: server
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose convert --provider=openshift -o openshift.yml
      kompose.version: 1.18.0 (06a2e56)
    creationTimestamp: null
    labels:
      io.kompose.service: server
    name: server
  spec:
    replicas: 1
    selector:
      io.kompose.service: server
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: server
      spec:
        containers:
        - args:
          - npm
          - run
          - start
          env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "8080"
          image: ' '
          name: server
          ports:
          - containerPort: 8080
          resources: {}
          tty: true
          workingDir: /home/node/app
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - server
        from:
          kind: ImageStreamTag
          name: server:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: server
    name: server
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: mifonkon/node-server
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
kind: List
metadata: {}

